repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: check-docstring-first
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: https://github.com/ambv/black
    rev: 21.11b1
    hooks:
      - id: black
        args: [--config, ./pyproject.toml]
        language_version: python3.9
