name: Python check

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - uses: Gr1N/setup-poetry@v7

    - uses: actions/cache@v2
      id: venv-cache
      with:
        path: ~/.cache/pypoetry/virtualenvs
        key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}

    - uses: actions/cache@v2
      id: pre-commit-cache
      with:
        path: ~/.cache/pre-commit
        key: ${{ runner.os }}-pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}

    - name: Install dependencies
      run: poetry install
      if: steps.venv-cache.outputs.cache-hit != 'true'

    - name: Pre-commit check
      run: poetry run pre-commit run --all-files

    - name: Test with pytest
      run: poetry run pytest
